<?php

class SablonaEmailu
{
    public function vypisSablonu()
    {
        $vypisSablonu = '';
        $vypisSablonu .= '<!DOCTYPE html>';
        $vypisSablonu .= '<html lang="cs" xmlns="https://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com:office:office">';
        $vypisSablonu .= '<head>';
        $vypisSablonu .= '  <meta charset="utf-8">';
        $vypisSablonu .= '  <meta name="viewport" content="width=device-width,initial-scale=1">';
        $vypisSablonu .= '  <meta name="x-apple-disable-message-reformatting">';
        $vypisSablonu .= '  <!--[if !mso]><!-->';
        $vypisSablonu .= '  <meta http-equiv="X-UA-Compatible" content="IE=edge">';
        $vypisSablonu .= '  <!--<![endif]-->';
        $vypisSablonu .= '  <title>Odeslaná zpráva pro FIRMA</title>';
        $vypisSablonu .= '  <!--[if mso]>';
        $vypisSablonu .= '    <style type="text/css">';
        $vypisSablonu .= '      * {';
        $vypisSablonu .= '        font-family: sans-serif !important;';
        $vypisSablonu .= '      }';
        $vypisSablonu .= '    </style>';
        $vypisSablonu .= '    <noscript>';
        $vypisSablonu .= '    <xml>';
        $vypisSablonu .= '      <o:OfficeDocumentSettings>';
        $vypisSablonu .= '        <o:PixelsPerInch>96</o:PixelsPerInch>';
        $vypisSablonu .= '      </o:OfficeDocumentSettings>';
        $vypisSablonu .= '    </xml>';
        $vypisSablonu .= '    </noscript>';
        $vypisSablonu .= '  <![endif]-->';
        $vypisSablonu .= '  <!--[if !mso]><!-->';
        $vypisSablonu .= '    <!-- insert web font reference, eg: <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet" type="text/css"> -->';
        $vypisSablonu .= '  <!--<![endif]-->';
        $vypisSablonu .= '  <style type="text/css">';
        $vypisSablonu .= '      html,';
        $vypisSablonu .= '      body {';
        $vypisSablonu .= '        margin: 0 auto !important;';
        $vypisSablonu .= '        padding: 0 !important;';
        $vypisSablonu .= '        height: 100% !important;';
        $vypisSablonu .= '        width: 100% !important;';
        $vypisSablonu .= '      }';
        $vypisSablonu .= '      * {';
        $vypisSablonu .= '          -ms-text-size-adjust: 100%;';
        $vypisSablonu .= '          -webkit-text-size-adjust: 100%;';
        $vypisSablonu .= '      }';
        $vypisSablonu .= '      div[style*="margin: 16px 0"] {';
        $vypisSablonu .= '          margin:0 !important;';
        $vypisSablonu .= '      }';
        $vypisSablonu .= '      table,';
        $vypisSablonu .= '      td {';
        $vypisSablonu .= '          mso-table-lspace: 0pt !important;';
        $vypisSablonu .= '          mso-table-rspace: 0pt !important;';
        $vypisSablonu .= '      }';
        $vypisSablonu .= '      table {';
        $vypisSablonu .= '          border-spacing: 0 !important;';
        $vypisSablonu .= '          border-collapse: collapse !important;';
        $vypisSablonu .= '          table-layout: fixed !important;';
        $vypisSablonu .= '          Margin: 0 auto !important;';
        $vypisSablonu .= '      }';
        $vypisSablonu .= '      table table table {';
        $vypisSablonu .= '          table-layout: auto;';
        $vypisSablonu .= '      }';
        $vypisSablonu .= '      img {';
        $vypisSablonu .= '          -ms-interpolation-mode:bicubic;';
        $vypisSablonu .= '      }';
        $vypisSablonu .= '      .mobile-link--footer a,';
        $vypisSablonu .= '      a[x-apple-data-detectors] {';
        $vypisSablonu .= '          color:inherit !important;';
        $vypisSablonu .= '          text-decoration: underline !important;';
        $vypisSablonu .= '      }';
        $vypisSablonu .= '      .box-shaddow {';
        $vypisSablonu .= '           -moz-box-shadow: 0px 0px 25px #dadada;';
        $vypisSablonu .= '           -webkit-box-shadow: 0px 0px 25px #dadada;';
        $vypisSablonu .= '           -ms-box-shadow: 0px 0px 25px #dadada;';
        $vypisSablonu .= '           box-shadow: 0px 0px 25px #dadada;';
        $vypisSablonu .= '      }';
        $vypisSablonu .= '  </style>';
        $vypisSablonu .= '  <style type="text/css">';
        $vypisSablonu .= '      .button-td,';
        $vypisSablonu .= '      .button-a {';
        $vypisSablonu .= '          transition: all 100ms ease-in;';
        $vypisSablonu .= '      }';
        $vypisSablonu .= '      .button-td:hover,';
        $vypisSablonu .= '      .button-a:hover {';
        $vypisSablonu .= '          background: #555555 !important;';
        $vypisSablonu .= '          border-color: #555555 !important;';
        $vypisSablonu .= '      }';
        $vypisSablonu .= '  </style>';
        $vypisSablonu .= '</head>';
        $vypisSablonu .= '<body width="100%" bgcolor="#fafafa" style="Margin: 0;">';
        $vypisSablonu .= '    <center style="width: 100%; background: #fafafa;">';
        $vypisSablonu .= '        <div class="box-shaddow" style="max-width: 600px; margin: auto;">';
        $vypisSablonu .= '            <!--[if (gte mso 9)|(IE)]>';
        $vypisSablonu .= '            <table cellspacing="0" cellpadding="0" border="0" width="600" align="center">';
        $vypisSablonu .= '            <tr>';
        $vypisSablonu .= '            <td>';
        $vypisSablonu .= '            <![endif]-->';
        $vypisSablonu .= '            <table cellspacing="0" cellpadding="0" border="0" align="center" width="100%" style="max-width: 600px;">';
        $vypisSablonu .= '                <tr>';
        $vypisSablonu .= '                  <td style="background-color: #ffffff; padding: 10px 0; text-align: center">';
        $vypisSablonu .= '                    <a href="https://www.example.com/">';
        $vypisSablonu .= '                      <img src="https://www.example.com/mediafile/loga/logo-firma-1000x150.png" width="200" height="30" alt="FIRMA s.r.o." border="0">';
        $vypisSablonu .= '                    </a>';
        $vypisSablonu .= '                  </td>';
        $vypisSablonu .= '                </tr>';
        $vypisSablonu .= '            </table>';
        $vypisSablonu .= '            <table cellspacing="0" cellpadding="0" border="0" align="center" bgcolor="#ffffff" width="100%" style="max-width: 600px;">';
        $vypisSablonu .= '                <tr>';
        $vypisSablonu .= '                    <td>';
        $vypisSablonu .= '                      <img src="https://www.example.com/mediafile/hero-image-01-600x256.jpg" width="600" height="" alt="Jsme profesionálové v oblasti čerpacích stanic" border="0" align="center" style="width: 100%; max-width: 600px;">';
        $vypisSablonu .= '                    </td>';
        $vypisSablonu .= '                </tr>';
        $vypisSablonu .= '                <tr>';
        $vypisSablonu .= '                    <td>';
        $vypisSablonu .= '                        <table cellspacing="0" cellpadding="0" border="0" width="100%">';
        $vypisSablonu .= '                            <tr>';
        $vypisSablonu .= '                                <td style="padding: 40px 20px; font-family: sans-serif; font-size: 12px; mso-height-rule: exactly; line-height: 20px; color: #555555;">';
        $vypisSablonu .= '                                    <h1 style="font-size: 1.4em;">Odeslaná zpráva pro FIRMA&nbsp;s.r.o.</h1>';
        $vypisSablonu .= '                                    <br><br>';
        $vypisSablonu .= '                                    Odesílatel: <strong>{{email_odesilatel}}</strong>';
        $vypisSablonu .= '                                    <br><br>';
        $vypisSablonu .= '                                    E-mail odesílatele: <strong>{{email_adresa}}</strong>';
        $vypisSablonu .= '                                    <br><br>';
        $vypisSablonu .= '                                    Zpráva:';
        $vypisSablonu .= '                                    <br>';
        $vypisSablonu .= '                                    {{email_zprava}}';
        $vypisSablonu .= '                                    <br><br>';
        $vypisSablonu .= '                                    <hr style="border: none; border-top: 1px solid #dadada;">';
        $vypisSablonu .= '                                </td>';
        $vypisSablonu .= '                            </tr>';
        $vypisSablonu .= '                            <tr>';
        $vypisSablonu .= '                                <td style="padding: 0; font-family: sans-serif; font-size: 12px; mso-height-rule: exactly; line-height: 20px; color: #ffffff;">';
        $vypisSablonu .= '                                    <table cellspacing="0" cellpadding="0" border="0" align="center" style="margin: auto !important; width: 100%;">';
        $vypisSablonu .= '                                        <tr style="background: #87B4C8;">';
        $vypisSablonu .= '                                            <td style="background: #87B4C8; text-align: center; padding: 10px; width: 25%;">';
        $vypisSablonu .= '                                                  <img src="https://www.example.com/mediafile/stanice_letovice_01.jpg" width="100" height="100" alt="Ukázka naší práce" border="0">';
        $vypisSablonu .= '                                                  <br>Stanice v Letovicích';
        $vypisSablonu .= '                                            </td>';
        $vypisSablonu .= '                                            <td style="background: #87B4C8; text-align: center; padding: 10px; width: 25%;">';
        $vypisSablonu .= '                                                  <img src="https://www.example.com/mediafile/stanice_policka_01.jpg" width="100" height="100" alt="Ukázka naší práce" border="0">';
        $vypisSablonu .= '                                                  <br>Stanice v Poličce';
        $vypisSablonu .= '                                            </td>';
        $vypisSablonu .= '                                            <td style="background: #87B4C8; text-align: center; padding: 10px; width: 25%;">';
        $vypisSablonu .= '                                                  <img src="https://www.example.com/mediafile/stanice_turany_letiste_01.jpg" width="100" height="100" alt="Ukázka naší práce" border="0">';
        $vypisSablonu .= '                                                  <br>Letiště v Tuřanech';
        $vypisSablonu .= '                                            </td>';
        $vypisSablonu .= '                                            <td style="background: #87B4C8; text-align: center; padding: 10px; width: 25%;">';
        $vypisSablonu .= '                                                  <img src="https://www.example.com/mediafile/stanice-dopaz-letovice_01.jpg" width="100" height="100" alt="Ukázka naší práce" border="0">';
        $vypisSablonu .= '                                                  <br>Stanice v Letovicích';
        $vypisSablonu .= '                                            </td>';
        $vypisSablonu .= '                                        </tr>';
        $vypisSablonu .= '                                    </table>';
        $vypisSablonu .= '                                </td>';
        $vypisSablonu .= '                            </tr>';
        $vypisSablonu .= '                            <tr>';
        $vypisSablonu .= '                                <td style="padding: 0; font-family: sans-serif; font-size: 12px; mso-height-rule: exactly; line-height: 20px; color: #555555;">';
        $vypisSablonu .= '                                    <br><br>';
        $vypisSablonu .= '                                    <table cellspacing="0" cellpadding="0" border="0" align="center" style="Margin: auto;">';
        $vypisSablonu .= '                                        <tr>';
        $vypisSablonu .= '                                            <td style="border-radius: 10px; background: #87B4C8; text-align: center;" class="button-td">';
        $vypisSablonu .= '                                                <a href="https://www.example.com/" style="background: #87B4C8; border: 15px solid #87B4C8; font-family: sans-serif; font-size: 25px; line-height: 1.1; text-align: center; text-decoration: none; display: block; border-radius: 3px; font-weight: bold;" class="button-a">';
        $vypisSablonu .= '                                                    &nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#ffffff;">Navštívit</span> <span style="color:#ffffff;">FIRMA</span><span style="color: #F59B4B;">.</span><span style="color:#000000;">cz</span>&nbsp;&nbsp;&nbsp;&nbsp;';
        $vypisSablonu .= '                                                </a>';
        $vypisSablonu .= '                                            </td>';
        $vypisSablonu .= '                                        </tr>';
        $vypisSablonu .= '                                    </table>';
        $vypisSablonu .= '                                    <br><br>';
        $vypisSablonu .= '                                    <table cellspacing="0" cellpadding="0" border="0" align="center" style="Margin: auto;">';
        $vypisSablonu .= '                                        <tr style="background: #ffffff;">';
        $vypisSablonu .= '                                            <td style="background: #ffffff; text-align: center; padding: 15px; width: 25%;">';
        $vypisSablonu .= '                                            </td>';
        $vypisSablonu .= '                                            <td style="background: #ffffff; text-align: center; padding: 15px; width: 25%;">';
        $vypisSablonu .= '                                                <a href="https://www.facebook.com/firma/" style="font-family: sans-serif; font-size: 13px; line-height: 1.1; text-align: center; text-decoration: none; display: block;font-weight: bold;">';
        $vypisSablonu .= '                                                  <img src="https://example.com/mediafile/loga/icon-facebook-gradient.png" width="50" height="50" alt="FIRMA na Facebooku" border="0">';
        $vypisSablonu .= '                                                </a>';
        $vypisSablonu .= '                                            </td>';
        $vypisSablonu .= '                                            <td style="background: #ffffff; text-align: center; padding: 15px; width: 25%;">';
        $vypisSablonu .= '                                                <a href="https://www.instagram.com/firma/" style="font-family: sans-serif; font-size: 13px; line-height: 1.1; text-align: center; text-decoration: none; display: block;font-weight: bold;">';
        $vypisSablonu .= '                                                  <img src="https://example.com/mediafile/loga/icon-instagram-gradient.png" width="50" height="50" alt="FIRMA na Instagramu" border="0">';
        $vypisSablonu .= '                                                </a>';
        $vypisSablonu .= '                                            </td>';
        $vypisSablonu .= '                                            <td style="background: #ffffff; text-align: center; padding: 15px; width: 25%;">';
        $vypisSablonu .= '                                            </td>';
        $vypisSablonu .= '                                        </tr>';
        $vypisSablonu .= '                                    </table>';
        $vypisSablonu .= '                                </td>';
        $vypisSablonu .= '                            </tr>';
        $vypisSablonu .= '                        </table>';
        $vypisSablonu .= '                    </td>';
        $vypisSablonu .= '                </tr>';
        $vypisSablonu .= '            </table>';
        $vypisSablonu .= '        </div>';
        $vypisSablonu .= '        <div style="max-width: 600px; margin: auto;">';
        $vypisSablonu .= '            <table cellspacing="0" cellpadding="0" border="0" align="center" width="100%" style="max-width: 680px;">';
        $vypisSablonu .= '                <tr>';
        $vypisSablonu .= '                    <td style="padding: 40px 10px;width: 100%;font-size: 12px; font-family: sans-serif; mso-height-rule: exactly; line-height:18px; text-align: center; color: #888888;">';
        $vypisSablonu .= '                        <br><br>';
        $vypisSablonu .= '                        Provozovatel portálu: <a href="https://www.example.com" style="color: #555555; text-decoration: none;">FIRMA s.r.o.</a><br><span class="mobile-link--footer">Znojmo</span><br><span><a href="calto:00420515225257" style="color: #555555; text-decoration: none;">tel.:&nbsp;(+420)&nbsp;515&nbsp;225&nbsp;257</a></span>';
        $vypisSablonu .= '                        <br><br>';
        $vypisSablonu .= '                    </td>';
        $vypisSablonu .= '                </tr>';
        $vypisSablonu .= '            </table>';
        $vypisSablonu .= '            <!--[if (gte mso 9)|(IE)]>';
        $vypisSablonu .= '            </td>';
        $vypisSablonu .= '            </tr>';
        $vypisSablonu .= '            </table>';
        $vypisSablonu .= '            <![endif]-->';
        $vypisSablonu .= '        </div>';
        $vypisSablonu .= '        <a href="https://www.flaticon.com/free-icons/instagram" title="instagram icons" style="margin-top: 40px;font-size: 10px;">Použité ikony: Instagram icons created by Freepik - Flaticon</a>';
        $vypisSablonu .= '    </center>';
        $vypisSablonu .= '</body>';
        $vypisSablonu .= '</html>';

        return $vypisSablonu;
    }
}
